from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, HRFlowable
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
import os
import datetime

def generate_pdf(record_id, cls, conf, risk, plot_path, save_dir):
    pdf_name = f"report_{record_id}.pdf"
    pdf_path = os.path.join(save_dir, pdf_name)

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72
    )
    
    story = []
    styles = getSampleStyleSheet()

    # --- Header ---
    # Title
    title_style = ParagraphStyle(
        'MedicalTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.darkblue,
        alignment=TA_CENTER,
        spaceAfter=12
    )
    story.append(Paragraph("Arrhythmia Detection Report", title_style))
    story.append(Spacer(1, 12))
    
    # Horizontal Line
    story.append(HRFlowable(width="100%", thickness=1, color=colors.black))
    story.append(Spacer(1, 12))

    # Meta Info (Date, Record ID)
    date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    meta_style = ParagraphStyle(
        'MetaInfo',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.gray,
        alignment=TA_RIGHT
    )
    story.append(Paragraph(f"Generated on: {date_str}", meta_style))
    story.append(Paragraph(f"Record ID: <b>{record_id}</b>", meta_style))
    story.append(Spacer(1, 30))

    # --- Results Table ---
    story.append(Paragraph("Analysis Results", styles['Heading2']))
    story.append(Spacer(1, 12))

    # Determine Risk Color
    risk_color_map = {
        "Normal": colors.green,
        "Low Risk": colors.orange,
        "High Risk": colors.red,
        "Critical": colors.darkred,
        "Uncertain": colors.gray
    }
    # Fallback to black if not found, or strict matching
    target_risk_color = risk_color_map.get(risk, colors.black)
    
    # Define Table Data
    data = [
        ["Parameter", "Value"],
        ["Prediction Class", cls],
        ["Confidence", f"{conf:.2f}"],
        ["Risk Assessment", risk]
    ]

    # Create Table
    # Column widths: 50% / 50% roughly
    t = Table(data, colWidths=[2.5*inch, 2.5*inch])
    
    # Table Style
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), colors.aliceblue),  # Header background
        ('TEXTCOLOR', (0, 0), (1, 0), colors.black),       # Header text
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),             # Center all
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),   # Header Font
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),    # Body background
        ('GRID', (0, 0), (-1, -1), 1, colors.lightgrey),   # Grid
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),       # Body Font
        ('FONTSIZE', (0, 1), (-1, -1), 11),
        ('TOPPADDING', (0, 1), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
        
        # Specific styling for Risk Cell (Row 3, Col 1) -> Value of Risk
        ('TEXTCOLOR', (1, 3), (1, 3), target_risk_color),
        ('FONTNAME', (1, 3), (1, 3), 'Helvetica-Bold'),
    ]))
    
    story.append(t)
    story.append(Spacer(1, 30))

    # --- Visualization ---
    if os.path.exists(plot_path):
        story.append(Paragraph("Heart Beat Visualization", styles['Heading2']))
        story.append(Spacer(1, 12))
        
        # Load Image
        # Aspect ratio handling: Assume the plot is wide. 
        # Making it fit within margins (A4 width ~8.27in, margins 1in each -> 6in usable)
        img = Image(plot_path, width=6*inch, height=3*inch) 
        img.hAlign = 'CENTER'
        story.append(img)
        story.append(Paragraph("Fig 1. Processed ECG signal segment used for prediction.", 
                               ParagraphStyle('Caption', parent=styles['Normal'], alignment=TA_CENTER, fontSize=9, fontName='Helvetica-Oblique')))
    
    story.append(Spacer(1, 50))

    # --- Footer ---
    story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
    story.append(Spacer(1, 6))
    
    footer_text = "DISCLAIMER: This report is generated by an AI model and is intended for reference only. It is not a substitute for professional medical diagnosis."
    story.append(Paragraph(footer_text, ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.gray, alignment=TA_CENTER)))

    # --- Watermark Function ---
    def draw_watermark(canvas, doc):
        canvas.saveState()
        canvas.setStrokeColor(colors.lightgrey)
        canvas.setLineWidth(5)
        canvas.setStrokeAlpha(0.3)  # Transparency
        
        # Draw a stylized ECG heartbeat trace across the center
        # Coordinates (x, y)
        w, h = A4
        mid_y = h / 2
        
        path = canvas.beginPath()
        path.moveTo(0, mid_y)
        path.lineTo(w * 0.3, mid_y)           # Baseline
        path.lineTo(w * 0.32, mid_y + 20)     # P wave
        path.lineTo(w * 0.34, mid_y)          # Baseline
        path.lineTo(w * 0.35, mid_y - 10)     # Q wave
        path.lineTo(w * 0.38, mid_y + 100)    # R wave peak
        path.lineTo(w * 0.41, mid_y - 30)     # S wave
        path.lineTo(w * 0.43, mid_y)          # Baseline
        path.lineTo(w * 0.46, mid_y + 30)     # T wave
        path.lineTo(w * 0.49, mid_y)          # Baseline
        path.lineTo(w, mid_y)                 # End line
        
        canvas.drawPath(path, stroke=1, fill=0)
        
        # Add Text
        canvas.translate(w/2, h/2)
        canvas.rotate(45)
        canvas.setFillColor(colors.lightgrey)
        canvas.setFillAlpha(0.2)
        canvas.setFont("Helvetica-Bold", 60)
        canvas.drawCentredString(0, -150, "ECG ANALYSIS")
        
        canvas.restoreState()

    # Build PDF with Watermark
    doc.build(story, onFirstPage=draw_watermark, onLaterPages=draw_watermark)
    
    return pdf_name
